adding roll up page theme colors
mapzen/styleguide pull request #545
Opened 2017-10-25 21:31 UTC by souperneon

cc @kkowalsky

2017-10-26 17:57 UTC, rfriberg commented
Thanks @souperneon!  I'm excited to have these extra colors available.

2017-10-30 15:59 UTC, rfriberg requested changes

2017-10-30 15:59 UTC, rfriberg commented on src/stylesheets/project_specific/styleguidepage/styleguidepage.scss
> +  background-color: #366026;
Can you replace the hex values with variables?  It'll be easier for updating later, if needed.

e.g.:
```
.mz-forestgreen-1 {
    background-color: $mz-forestgreen-1;
}
```

2017-10-30 16:21 UTC, souperneon commented on src/stylesheets/project_specific/styleguidepage/styleguidepage.scss
> +  background-color: #366026;
Doh!

2017-10-30 16:26 UTC, rfriberg approved these changes
:chefs_kiss:

2017-10-30 18:14 UTC, merged